### ISSUE TITLE
Customizable metadata when writing COPC files

### ISSUE THREAD

**Issue by wonder-sk** [hobuinc/untwine#139]
Some pieces of metadata are not kept when a LAS/LAZ file is processed with untwine:
- global encoding - the bit on GPS time shift is not preserved
- creation time - hardcoded to day 1 of year 1
- X/Y/Z offset - untwine picks the offset itself (in the center of the data) rather than reusing the original one

**Comment by abellgithub** [comment]
Is this request just in the case of a single input file?

**Comment by hobu** [comment]
> Is this request just in the case of a single input file?

Yeah. I was thinking of providing options to allow people to explicitly set the metadata rather than trying to mimic PDAL's `forward` behavior, which would be fraught.

**Comment by uclaros** [comment]
> Is this request just in the case of a single input file?

For the cases of a single input file, which is always the case in QGIS, I think it makes sense to default to the following:
- preserving the gps time bit, as it allows proper interpretation of gps times for the file
- Creation year/day for a single file should be updated, as the las spec states: `Day, expressed as an unsigned short, on which this file was created.` _This file_ applies to the copc output file. 
- Since the scaling is preserved, it makes sense to also preserve the offsets.

I consider options to explicitly set the metadata as a quite advanced feature that the majority of users shouldn't need to deal with, as long as sane defaults are used.
