### ISSUE TITLE
Possible to compress tmp files?

### ISSUE THREAD

**Issue by craigds** [hobuinc/untwine#174]
We've been running untwine over some fairly hefty layers and are finding it generates over 300GB of temp LAS before slimming down to a modestly sized COPC file output.

Could the temp files be compressed as LAZ, or would doing so fundamentally break untwine's algorithm / make it horrendously slow somehow?

I confess I don't really understand the internals enough to say whether this is a silly idea or not. Thanks

**Comment by hobu** [comment]
Use the `--dims` option to control the list of dimensions you actually need to cache. You'll have to accumulate statistics a priori to know which ones actually have data in them, but if your data only has a few dimensions with actual content in them, this is the best way to limit what's cached.

We can't compress the cache because it is memory-mapped.

**Comment by craigds** [comment]
Thanks, that makes sense. I don't think we can use `--dims` since we need to preserve the dimensions from the input files into the output COPC, so we'll need to just have more disk available.

**Comment by hobu** [comment]
> preserve the dimensions

If there's no data in those dimensions, you can skip caching them at least. The slots might get written back out into the COPC file, but if you know there's no GPStime or PointSourceId, you can save quite a bit of disk cache space by specifying `--dims`

**Comment by craigds** [comment]
We do have statistics on the data involved but no dice there (at least in the troublesome dataset we're working with at the moment); all dimensions are populated.
